sudo: required

services:
    - docker


before_install:
    - docker build -t safialyounis/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run safialyounis/react-test npm run test -- --coverage

after_success:
  
    - docker image tag complex_nginx:latest safialyounis/multi_nginx

    #log in to docker cli
    - echo "$DOCKER_PASSWORD" | docke login -u "$DOCKER_ID" --PASSWORD-stdin
    # to take those images and put them to docker hup
   
    - docker push safialyounis/multi-nginx
   

